name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      run: |
        cd app
        docker build -t ${{ secrets.ECR_URL }}:latest .
        docker push ${{ secrets.ECR_URL }}:latest

    - name: Deploy to Kubernetes
      run: |
        aws eks update-kubeconfig --region us-west-2 --name portfolio-cluster
        kubectl apply -f k8s/
